server:
  port: 13900
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: code-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://115.28.186.77:30306/db_dop_code?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: dop
    password: Dop_mysql_12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 10
    max-idle: 5
    min-idle: 5
    initial-size: 5
    max-wait: 10000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: true
spring.jackson.serialization.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false

project:
  host: open.dop.clsaa.com/@project.name@
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
  name: @project.name@
  description: @project.description@
  url: @project.url@
swagger.enable: true
eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
    #续约更新时间间隔
    lease-renewal-interval-in-seconds: 5
    #续约到期时间
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://121.42.13.103:32129/eureka
    registry-fetch-interval-seconds: 5 #定时刷新本地缓存
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  ServerListRefreshInterval: 2000
logging.path: ./logs/${spring.application.name}

mybatis:
  type-aliases-package: com.clsaa.dop.server.code.model.po
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mapper/config/sqlMapConfig.xml

message:
  mq:
    RocketMQ:                                     #RocketMQ相关配置
      namesrvAddr: rocketmq.dop.clsaa.com:9876    #name-server地址与端口,多个可用分号隔开
      groupName:  DOP_MESSAGE_PRODUCER_GROUP      #生产者组名称
      instanceName: DOP_MESSAGE                   #要发送到的MQ集群
      maxMessageSize: 131072 # 1024*128           #最大消息长度
      sendMessageTimeout: 10000                   #消息发送超时时间
      registerAccountTopic: REGISTER_ACCOUNT_QUEUE  #注册消息队列
      registerAccountConsumerGroup: REGISTER_ACCOUNT_CONSUMER_GROUP  #注册消费者组
      updateAccountTopic: UPDATE_ACCOUNT_QUEUE  #修改密码消息队列
      updateAccountConsumerGroup: UPDATE_ACCOUNT_CONSUMER_GROUP #修改密码消费者组
